- name: Uninstall xone
  become: true
  command:
    chdir: /tmp/xone
    cmd: ./uninstall.sh
  register: xone_uninstall
  when: xone_uninstall.rc is defined # checks if it is already installed
  changed_when: xone_uninstall.rc == 0
