---
- name: Update packages
  apt:
    update_cache: true
    upgrade: true
  become: true

- name: Install input-remapper with apt
  apt:
    name: input-remapper
    state: present
  become: true

- name: Make sure input remapper is running
  ansible.builtin.systemd:
    state: started
    name: input-remapper

- name: trackball config
  copy:
    src: kensington_trackball_button_switch.json
    dest: "~/.config/input-remapper/presets/Kensington Expert Wireless TB Mouse/kensington_trackball_button_switch.json"
    mode: 0664

- name: load input input-remapper
  command: input-remapper-control --command autoload
  register: result
  changed_when: result.rc == 0
