---
- name: Check distribution
  assert:
    that:
      - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      - ansible_distribution_major_version | int >= 16
    msg: "This playbook is intended for Debian or Ubuntu versions 16 or later."

- name: Add Wezterm GPG key
  ansible.builtin.get_url:
    url: "https://apt.fury.io/wez/gpg.key"
    dest: "/usr/share/keyrings/wezterm-fury.gpg"
    owner: root
    mode: '0644'
  register: gpg_key_result
  ignore_errors: true
  changed_when: false

- name: Add Wezterm APT repository
  ansible.builtin.lineinfile:
    path: "/etc/apt/sources.list.d/wezterm.list"
    line: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"
    create: true
    state: present
    owner: root
    group: root
    mode: '0644'
  register: apt_repo_result
  ignore_errors: true
  changed_when: false

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: gpg_key_result is succeeded and apt_repo_result is succeeded

- name: Install Wezterm package
  ansible.builtin.apt:
    name: wezterm
    state: present
  when: gpg_key_result is succeeded and apt_repo_result is succeeded

- name: Check if wezterm config file exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/wezterm/wezterm.lua"
  register: wezterm_config

- name: Create directory if it doesn't exist
  file:
    path: "{{ ansible_env.HOME }}/.config/wezterm"
    state: directory
    mode: 0755
  when: not wezterm_config.stat.exists

- name: Copy new config file
  copy:
    src: wezterm.config
    dest: "{{ ansible_env.HOME }}/.config/wezterm/wezterm.lua"
    mode: 0755
  when: not wezterm_config.stat.exists
