---
- name: Download Powerlevel10k fonts
  git:
    repo: "https://github.com/Dr4kn/ansible-private-files"
    dest: "/tmp/ansible-private-files"
    version: main
    depth: 1

- name: Update font cache
  command: fc-cache -f -v
  register: font_cache
  changed_when: font_cache.rc == 0
