---
- name: Install vim
  package:
    name: vim
    state: present

- name: Create for vim a backup, swap and undo directory if they don't exist
  file:
    path: ~/.vim/{{ item }}
    state: directory
    mode: "0777"
  with_items:
    - .backup
    - .swp
    - .undo

- name: vim config
  copy:
    src: .vimrc
    dest: ~/.vim/.vimrc
    mode: 0664

- name: check if ideavimrc link already existsts
  stat: path=~/.ideavimrc
  register: link

- name: IntelliJ vim config
  file:
    src: ~/.vim/.vimrc
    dest: ~/.ideavimrc
    state: link
  when: link.stat.islnk is not defined
