---
- name: Install zsh
  apt:
    name: zsh
    state: present
    update_cache: true

# - block:
#     - name: change user shell to zsh
#       vars:
#         username: "{{ ansible_user_id }}"
#       user:
#         name: "{{ username }}"
#         shell: /bin/zsh
#   become: false

# - block:
#     - name: change root shell to zsh
#       vars:
#         username: "{{ ansible_user_id }}"
#       user:
#         name: "{{ username }}"
#         shell: /bin/zsh
#   become: true

- name: Download ohmyzsh installer
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/zsh-installer.sh
    mode: 755

- name: Execute the ohmyzsh installer
  shell:
    chdir: /tmp
    cmd: ./zsh-installer.sh
  # changed_when: "The $ZSH folder already exists"
# - name: Remove the ohmyzsh installer
#   file:
#     path: /tmp/zsh-installer.sh
#     state: absent
