---
- name: Get current user
  command: whoami
  register: current_user
  changed_when: current_user.rc == 0

- name: Install zsh
  become: true
  package:
    name: zsh
    state: present

- block:
    - name: change user shell to zsh
      user:
        name: "{{ item }}"
        shell: /bin/zsh
      with_items:
        - "{{ current_user.stdout }}"
        - root

    - name: add .zshrc config
      copy:
        src: .zshrc
        dest: "{{ item }}/.zshrc"
        mode: 0644
      with_items:
        - "/home/{{ current_user.stdout }}"
        - /root
  become: true