---
- block:
    - name: Update packages
      apt:
        update_cache: true
        upgrade: true

    - name: Install packages
      package:
        name:
          - flatpak
          - git
          - neofetch
          - vim
          - gnome-extensions-app
        state: present
  become: true

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  with_items:
    - com.spotify.Client
    - org.mozilla.firefox
    - org.onlyoffice.desktopeditors
    - org.gimp.GIMP
    - com.bitwarden.desktop
    - md.obsidian.Obsidian
    - com.calibre_ebook.calibre
    - io.mpv.Mpv
    - io.github.celluloid_player.Celluloid
    - org.videolan.VLC
    - de.haeckerfelix.Fragments
    - org.chromium.Chromium
