---
- name: change git config
  copy:
    src: .gitconfig
    dest: ~/.gitconfig
    mode: 0664

- name: kensington trackball button switch as bin
  copy:
    src: kensington_trackball.bash
    dest: /usr/bin/kensington_trackball
    mode: 0751
  register: trackball
  become: true

- name: Create cron job that removes unused flatpak dependencies
  cron:
    name: "remove flatpak dependencies that aren't used anymore"
    special_time: daily
    job: "yes | flatpak uninstall --unused"

- name: install vim and add all the configuration
  import_tasks: vim.yml
